use_frameworks!

platform :ios, '10.0'

target 'WSNavigationDrawerSwift_Example' do
  pod 'WSNavigationDrawerSwift', :path => '../'

  target 'WSNavigationDrawerSwift_Tests' do
    inherit! :search_paths

    
  end
end
